# Generated by Django 5.0.7 on 2024-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=13)),
                ("desc", models.TextField()),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CT", "Chattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("UP", "Uttar Pradesh"),
                            ("UK", "Uttarakhand"),
                            ("WB", "West Bengal"),
                        ],
                        default="UP",
                        max_length=10,
                    ),
                ),
                ("pincode", models.CharField(max_length=20)),
                ("date", models.DateField()),
            ],
        ),
    ]
